# Generated by Django 5.0.6 on 2024-08-07 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item_itemimage_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='content',
            new_name='description',
        ),
    ]
